synergy-design-system/synergy-design-system

CONTRIBUTING.md
package.json
packages/components/CHANGELOG.md
packages/components/package.json
packages/css/CHANGELOG.md
packages/css/package.json
packages/design-tokens/CHANGELOG.md
packages/design-tokens/package.json
packages/docs/.storybook/sds-theme.ts
packages/docs/CHANGELOG.md
packages/docs/package.json
packages/eslint-config-sds/CHANGELOG.md
packages/eslint-config-sds/package.json
packages/icons/CHANGELOG.md
packages/icons/package.json
packages/stylelint-config-sds/CHANGELOG.md
packages/stylelint-config-sds/package.json

This PR adjusts the package.json `author` field for all to be published packages. It also removes the `contributors` key in the root package.json as this is never published at all.
The authorship of the library is done through SICKs Global UX Community, not the Frontend Team alone. This change should reflect the ownership of the packages.
Closes https://github.com/SickDesignSystem/Internal/issues/17
Closes https://github.com/SickDesignSystem/Internal/issues/14
Please have a look at the corresponding **package.json** files in this PR. Other files where just updated to set the new repository base url to `/synergy` instead of `/sds`.

✨ Docs(all) #17: Adjusted package.json author field

---

.github/ISSUE_TEMPLATE/component-request-feature.md
.github/ISSUE_TEMPLATE/component-request-new-component.md
.github/ISSUE_TEMPLATE/generic-bug.md
.github/ISSUE_TEMPLATE/generic-docs.md
.github/ISSUE_TEMPLATE/generic-feature.md
CHANGELOG.md

This PR adjusts the issue templates to match [conventional changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular#type) style.
Closes https://github.com/SickDesignSystem/Internal/issues/18
As discussed, I have added the emojis directly to the issue templates to make them easier to use. If this does not fit our needs, we will remove them at a later point of time.

✨ Feat(core) - #18: Adjusted issue titles to use conventional changelog

---

packages/_internal/eslint-config-syn/package.json
packages/_internal/stylelint-config-syn/package.json
packages/assets/package.json
packages/components/package.json
packages/tokens/package.json

This PR adjusts some meta field information in various packages in package.json.
Closes #80 
Closes #83 
Just take a look at the package.json files in the PR. Also follow the instructions at #83 to see the current behaviour.

fix: 🤔 Fix multiple errors in package.json

---

packages/docs/.storybook/preview.ts
packages/docs/src/decorators/StopAnimation.ts

This PR removes animations from `<syn-spinner />` when used in chromatic environments. It also tries to do the same by setting the animation timeouts for other animations to `-1`, effectively removing them.
Closes #133.
- The functionality as described in `packages/docs/src/decorators/StopAnimation.ts` will work, but some components of shoelace bring their own timings, hence the override for `syn-spinner`.
- Run `pnpm i -r && pnpm build`
- Move to `packages/docs` and start via `pnpm start`
- Open the Story SynButton/Loading (http://localhost:6006/?path=/story/components-syn-button--loading). You should see the spin icon rotates
- Exchange the url for http://localhost:6006/?path=/story/components-syn-button--loading&chromatic=true. With `chromatic=true`, you should …

fix: 🤔 Chromatic treats buttons with spinners as new screenshot every time

---

packages/tokens/src/figma-tokens/semantic/input.json

This pull request fixes the focus ring offset issue in the code. The previous offset value was set twice, causing the focus ring to be misaligned. This PR updates the offset value to the correct spacing value, ensuring that the focus ring is properly aligned.
Closes #158

fix: 🐛 fix focus ring offset

---

packages/components/package.json
packages/components/scripts/jobs/createChecksums.js

This pull request updates the `package.json` file with the new checksums for the `angular`, `react`, and `vue` packages. The checksums are obtained by running `git rev-parse HEAD:packages/{project}` for each package. This ensures that the checksums are always up to date with the latest commit in each package and is hopefully more robust and performant in comparison to (p)npm publish.

chore: 🔧 use new checksum creation

---

.vscode/settings.json
CONTRIBUTING.md
packages/docs/.eslintrc
packages/docs/.storybook/preview.ts
packages/docs/README.md
packages/docs/src/helpers/component.ts
packages/docs/stories/components/button.stories.ts
packages/docs/stories/components/checkbox.stories.ts
packages/docs/stories/components/default-icons.stories.ts
packages/docs/stories/components/icon.stories.ts
packages/docs/stories/components/input.stories.ts
packages/docs/stories/components/radio-group.stories.ts
packages/docs/stories/components/radio.stories.ts
packages/docs/stories/components/switch.stories.ts
packages/docs/stories/components/textarea.stories.ts

The amount of screenshots taken by chromatic needs to be limited to avoid running out of screenshots.
Closes [#55](https://github.com/synergy-design-system/Internal/issues/55)

chore: 🔧 Reduce chromatic load via bundled screenshot story

---

.github/workflows/quality-check.yml

The amount of screenshots taken by chromatic needs to be limited to avoid running out of screenshots.
To limit it, the github action for chromatic is no longer running when a pull request is in draft mode.
Closes https://github.com/synergy-design-system/Internal/issues/55
I created this PR with draft mode. With the changes to the ci cd, all jobs except the chromatic job were running.
After removing draft, all jobs were triggered again including the chromatic job.
**Draft mode:** 
See checks: https://github.com/synergy-design-system/synergy-design-system/actions/runs/7420881861/job/20193168020?pr=237
**After removing draft mode:**
see checks: https://github.com/synergy-design-system/synergy-design-system/actions/runs/7420943445/job/20193342098?pr=237

chore: 🔧 Reduce chromatic load via draft pull requests

---

packages/components/package.json
pnpm-lock.yaml

This PR fixes the warning "multiple versions of lit loaded" in the console when running the tests of the components package.
An old version of the _@open-wc/testing_ dependency was used, which still used the old lit version 2.
Fixes #173 
To test if this is fixed: 
- run `pnpm i -r`
- go into the components package `cd ./packages/components`
- run the tests `pnpm test`
This lines with "Multiple version of Lit...." should no longer be there

chore: 🤔 Fix "multiple versions of lit loaded" warning when running tests

---

packages/tokens/src/figma-tokens/semantic/input.json

The tokens of 'input.icon.icon-clearable' reference primitive tokens instead of core tokens. With this PR they are getting exchanged from "gray.500" to "neutral.500"
Closes [#228](https://github.com/synergy-design-system/synergy-design-system/issues/228)

fix: 🤔 Replace primitive tokens of 'input.icon.icon-clearable'

---

packages/_private/vue-demo/src/DemoForm.vue
packages/components/scripts/jobs/vue/createWrappers.js
packages/vue/src/components/SynVueButton.vue
packages/vue/src/components/SynVueCheckbox.vue
packages/vue/src/components/SynVueIcon.vue
packages/vue/src/components/SynVueIconButton.vue
packages/vue/src/components/SynVueInput.vue
packages/vue/src/components/SynVueRadio.vue
packages/vue/src/components/SynVueRadioButton.vue
packages/vue/src/components/SynVueRadioGroup.vue
packages/vue/src/components/SynVueSelect.vue
packages/vue/src/components/SynVueSwitch.vue
packages/vue/src/components/SynVueTag.vue
packages/vue/src/components/SynVueTextarea.vue

…nt component, fixed form handling in demo
This PR fixes an issue that initial data was not loaded correctly when using two way databinding as defined in our current vue demo. The initial data would not be used for the state of a given component, for example a checkbox that **should** be checked per default in the form **was** unchecked initially. The problem happened because we did not provide the initial `value` or `checked` prop for the component, making the binding work, but not the initial data.
I also stumbled around another problem by accident. `<SynVueSwitch />` was not enabled for two way databinding and did not participate in the forms. I also opted to adjust the Demos `synChange` handler to make sure data would not be set in a non-reactive way as we would like to test the …

fix: 🤔 Vue two way data binding does not honor the provided default value

---

packages/components/src/components/icon-button/icon-button.custom.styles.ts

This PR removes the `border-radius` from the `<syn-icon-button />` component.
Closes #341 
Just have a look at the chromatic stories. Everything else is unchanged.
Look into current chromatic stories and see if there are any visual changes:
- IconButton stories (all)
- Drawer (The close icon is a `<syn-icon-button />`
- Header (`<syn-icon-button />` is used in Meta-Navigation examples)
- Tags (`<syn-icon-button />` is used for the "remove tag" close icon)

fix: 🤔 syn-icon-button has a border-radius

---

packages/components/src/components/tag/tag.custom.styles.ts

This PR adds support for the border radius values included in https://github.com/synergy-design-system/synergy-design-system/pull/338. It sets the `border-radius` property for `<syn-tag />` to a default of `--syn-border-radius-small` for all sizes.
Closes #340 
Just have a look at the stories for `<syn-tag />` and `<syn-select />` with multiple.
- Check the changes in Chromatic.

feat: ✨ add border-radius and roundings to syn-tag

---

packages/components/src/components/menu/menu.custom.styles.ts

This PR changes the color of `<syn-divider />` elements that are slotted into `<syn-menu />`items.
Closes #369 
Just follow the regular procedure. Changed stories are `<syn-dropdown />` and `<syn-menu />`.
- Verify that the stories for `<syn-dropdown />` are displayed correctly.
- Verify that the stories for `<syn-menu />` are displayed correctly.

feat: ✨ syn-divider in syn-dropdown should have a color syn-color-neutral-200

---

packages/angular/src/components/dropdown.component.ts
packages/components/scripts/vendorism.js
packages/components/scripts/vendorism/custom/button.vendorism.js
packages/components/scripts/vendorism/custom/webTestRunner.vendorism.js
packages/components/src/components/button-group/button-group.component.ts
packages/components/src/components/button/button.styles.ts
packages/components/src/components/checkbox/checkbox.component.ts
packages/components/src/components/checkbox/checkbox.styles.ts
packages/components/src/components/dropdown/dropdown.component.ts
packages/components/src/components/icon/icon.component.ts
packages/components/src/components/input/input.component.ts
packages/components/src/components/input/input.styles.ts
packages/components/src/components/menu-item/submenu-controller.ts
packages/components/src/components/popup/popup.component.ts
packages/components/src/components/select/select.component.ts
packages/components/src/components/select/select.test.ts
packages/components/src/components/switch/switch.styles.ts
packages/components/src/internal/form.ts
packages/components/src/internal/scroll.ts
packages/components/src/themes/utility.css
packages/components/web-test-runner.config.js
packages/docs/.storybook/preview-head.html
packages/vue/src/components/SynVueDropdown.vue

This PR updates Shoelace to the latest version 2.15.0.
Closes #398 and #347 
The main changes from shoelace are:
- Added the `sync` property to <sl-dropdown> 
- Fixed a bug in <sl-icon> that did not properly apply mutators to spritesheets 
- Fixed a bug in .sl-scroll-lock causing layout shifts
- Fixed a bug in <sl-select> that caused the menu to not close when rendered in a shadow root
- Fixed a bug in the submenu controller that allowed two submenus to be open at the same time 
- Fixed a bug in <sl-select> where the tag size wouldn’t update with the control’s size 
- Fixed a bug in <sl-checkbox> and <sl-switch> where the color of the required content wasn’t applying correctly
- Fixed a bug in <sl-checkbox> where help text was incorrectly styled
- Fixed a bug in <sl-input> that prevented …

feat: ✨ upgrade shoelace to 2.15.0

---

packages/components/scripts/vendorism/custom/textarea.vendorism.js
packages/components/scripts/vendorism/replace-section.js
packages/components/src/components/textarea/textarea.component.ts

This PR prevents an error that may appear when removing the `<syn-textarea />` too fast from the DOM. This may especially happen in test frameworks (e.g. Karma), where the current behaviour lead to an error `Uncaught TypeError: Failed to execute 'unobserve' on 'ResizeObserver': parameter 1 is not of type 'Element'. thrown`.
Closes #435
- I have opted to rewrite the vendorism script in the new style and also add two new utility functions to make it easier in the future: `replaceSection` will replace a section with the same syntax as `removeSection`, whereas `replaceSections` will do the same given an array of replacements.
- There where some dangling css classes that where copied left overs from the input vendorism (prefix and suffix). Those are removed
- The fix is applied, too ;) …

fix: 🤔 syn-text-area may throw an error when unmounted too quick

---

packages/components/src/components/nav-item/nav-item.component.ts
packages/components/src/components/nav-item/nav-item.styles.ts

This PR fixes an issue that showed the wrong chevron position was used for `<syn-nav-items>` when having both a `href` and `chevron` attribute set.
Old behavior:
New behavior:
Closes #432 
The change does not have an associated story.
- Build world and start storybook
- Move to the docs page of `<syn-nav-item>`
- Set a `href` attribute and set `chevron` to true

fix: 🤔 chevron of syn-nav-item using wrong symbol

---

packages/components/src/components/checkbox/checkbox.custom.styles.ts

This PR fixes an issue that lead to broken line-heights for the label of `<syn-checkboxes>` when the label was displayed in multiple lines.
Closes #298 
The issue stems from the fact that Shoelace uses a fixed line-height value for the label that is set to the size of the checkboxes checkmark icon. When using a checkbox that has a multi-line label, this lead to the problem that spacing between the lines was too narrow.
A word on tokens: I was not able to use our token values for this as the margins are too narrow to tackle them this way.
1. Verify the bug exists in the current version of Synergy (e.g. in our own form-template at https://synergy-design-system.github.io/?path=/story/templates-forms--contact-form&globals=viewport:default)
2. Have a look at the storybook version of this PR. …

fix: 🤔 Syn-Checkbox uses wrong line-height when in multi-line mode

---

packages/components/src/components/header/header.styles.ts

This PR adds a fixed color of `--syn-typography-color-text` to the `<syn-header>` label prop.
Closes #483 
Just have a look at storybook, nothing fancy here.
Just have a look at storybook, nothing fancy here.

fix: 🤔 syn-header label uses wrong text color

---

packages/components/scripts/vendorism/custom/tab-group.vendorism.js
packages/components/src/components/tab-group/tab-group.component.ts

This PR adds a catch during unmount of the `<syn-tab-group>` that leads to errors when using the components in test environments.
```bash
Uncaught TypeError: Failed to execute 'unobserve' on 'ResizeObserver': parameter 1 is not of type 'Element'. thrown 
```
Closes #511

fix: 🤔 syn-tab-group may throw an error when unmounted too quick

---

packages/styles/package.json
pnpm-lock.yaml

This PR fixes an issue that `@synergy-design-system/styles` is not installable out of the box because of a wrong version specifier, as seen in this output:
```bash
npm info @synergy-design-system/styles peerDependencies
{ '@synergy-design-system/tokens': '2.2.0' }
```
The version of the tokens package is actually fixed until we push the package again. It should read `^2.2.0` instead of `2.2.0`.
Closes #539 
Nothing that much to do here, just check the change in `package.json`.

fix: 🤔 Styles package uses fixed peerDependency for tokens

---

packages/_private/react-demo/src/Layout.tsx
packages/_private/vanilla-demo/src/main.ts

This PR fixes an Issue when clicking a `syn-nav-item` in our vanilla demo.
Fixes #528 
Just smaller fixes for our vanilla demo. Makes icons clickable.
Spin up our local vanilla demo and check if you are able to click one of the icons in the `syn-side-nav`.

docs: 📘 Click listeners bleed implementation details to the outside

---

packages/components/scripts/vendorism/custom/details.vendorism.js
packages/components/scripts/vendorism/replace-section.js
packages/components/src/components/details/details.component.ts
packages/components/src/components/side-nav/side-nav.component.ts
packages/components/src/components/tab-group/tab-group.component.ts

This PR prevents two errors that may appear when removing the <syn-details /> or the <syn-side-nav/>  too fast from the DOM. This may especially happen in test frameworks (e.g. vitest), where the current behaviour leads to errors if using those both components.
Closes #556 
I also improved / rewrote the details.vendorism.js in this PR.
Can be tested with this vue test repo: https://github.com/kirchsuSICKAG/vue-test
To make the errors appear change the vitests environment from 'happy-dom' to 'jsdom'

fix: 🤔 syn-side-nav and syn-details may throw an error when unmounted too quick

---

packages/_private/react-demo/src/DemoForm.tsx
packages/components/scripts/vendorism/custom/icon-button.vendorism.js
packages/components/src/components/icon-button/icon-button.component.ts
packages/components/src/components/icon-button/icon-button.custom.styles.ts
packages/docs/stories/components/header.stories.ts
packages/docs/stories/components/icon-button.stories.ts

This PR fixes an issue with `<syn-icon-button>` not honoring its `currentColor` default setting. This seems to always have been faulty, resulting in issues like #450 that where resolved as usage errors, but where implementation errors on our side.
Closes #590 
I have provided a fix for the issue and opted to rewrite the css to make this work as we had to apply the `currentColor` value on the host directly anyways. This is not solvable with custom classes in the shadow root unfortunately.
Therefore, I have opted to adjust our selectors to use `:host` selectors instead of inline ones in the shadow root. The vendor scripts have been adjusted accordingly. The original classes for color styles have been removed for the sake of completeness.
I have also checked demos for `syn-dialog`, …

fix: 🐛 syn-icon-button is not honoring 'currentColor' correctly

---

packages/components/src/components/button/button.custom.styles.ts

This PR fixes the `font-weight` of `<syn-button>` (should be bold instead of semi-bold).
Closes #571 
This is a really small fix, but may lead to various layout shifts in different components (see Chromatic for results).
- Have a look at the changed code
- Check Chromatic for side effects.

fix: 🐛 Wrong font weight for text content in button

---

packages/components/src/components/prio-nav/prio-nav.component.ts
packages/components/src/components/prio-nav/prio-nav.test.ts

This fixes an issue that is very clear if the syn-prio-nav is not on the left edge of the viewport, where it will start displaying the dropdown menu a lot earlier than is needed.
It also makes sure to not take into account the size of the dropdown button unless the dropdown button is actually shown.
Also slightly related, the cache should probably be purged if the size of the elements change, but I'll perhaps tackle that at another point.
Closes #639 
This seems like it'd be quite easy to create a test for. Can someone point me in the right direction where to add such a test?

fix: 🐛 syn-prio-nav: priority menu position is always calculated from the absolute left of the document

---

packages/components/src/components/nav-item/nav-item.component.ts
packages/components/src/components/nav-item/nav-item.styles.ts
packages/components/src/components/nav-item/nav-item.test.ts
packages/components/src/components/prio-nav/prio-nav.component.ts
packages/components/src/components/prio-nav/prio-nav.test.ts
packages/components/src/components/prio-nav/utils.ts
packages/docs/stories/components/nav-item.stories.ts
packages/docs/stories/components/prio-nav.stories.ts
packages/tokens/src/figma-tokens/_docs.json

This PR acts as an umbrella for various tickets related to the `<syn-prio-nav>` and `<syn-nav-item>` components.
Closes #644 
Closes #582
Closes #631
Closes #410
Closes #409
Closes #630 
Closes #639
This PR is used to add multiple fixes to our navigation items. It is easier to review those tickets in one scope, so we created an umbrella ticket housing all changes.
The following list of steps describes all issues and their related tests:
Before: https://codepen.io/schilchSICKAG/pen/LYwGraY?editors=1110
After: http://localhost:6006/?path=/docs/components-syn-prio-nav--docs
tl;dr: When using a href attribute, the alignment must now always fit in horizontal mode. The default story of `<syn-prio-nav>` was adjusted to include a `<syn-nav-item>` with a href attribute to check this also in visual …

fix: 🐛 Various issues with syn-prio-nav

---

packages/components/scripts/vendorism/custom/tab-group.vendorism.js
packages/components/src/components/tab-group/tab-group.component.ts
packages/components/src/components/tab-group/tab-group.custom.test.ts

This PR prevents an error that may appear when removing the syn-tab-group too fast from the DOM. This may especially happen in test frameworks (e.g. vitest, karma), where the current behaviour leads to errors if using those component
Closes #652

fix: 🐛 syn-tab-group may throw an error when unmounted too quick

---

packages/docs/stories/components/card.stories.ts
packages/docs/stories/components/icon-default-icons.stories.ts
packages/docs/stories/templates/table.stories.tsx

This PR uses absolute paths to .jpg images used in stories and templates, so they are also available for codepen.
Additionally the loading of the default icons (https://synergy-design-system.github.io/?path=/docs/components-syn-icon-default-icons--docs) is improved via using the bundled icons as source for the syn-icon's. 
Previously not all icons where loaded initially , when going to the default icons page. And there were also a lot of error logs in the console because of too many fetch requests. See following image:
Closes #580 
- let it run locally and have a look at this page: http://localhost:6006/?path=/docs/components-syn-icon-default-icons--docs
all icons should have loaded directly (even the ones starting with `z`) and there should no longer be error logs in the console, which …

docs: 📚  some codepen assets are not loaded

---

packages/components/package.json

This PR adds a `default` fallback entry to our `@synergy-design-system/components` `package.json` file that allows the better usage of tooling and a graceful fallback for bundlers that do not understand esm syntax.
It also adds the `package.json` field to the export list so it is easy to use, for example for dynamically requiring it and obtaining the information.
Closes #594
Just have a look at the changed `package.json`. Create a new local version of the components package and check if it works with vite + webpack.

fix: 🐛 Add default entry for default export for better tooling compatibility

---

packages/components/scripts/vendorism/custom/alert.vendorism.js
packages/components/src/components/alert/alert.styles.ts

This PR fixes the problem, that the left border of the syn-alert no longer reaches the edges since the update to shoelace 2.17.0
This is done via removing the `overflow:hidden` as we haven't added the new `countdown` feature and therefore don't need the `overflow: hidden`
Closes #675 
Check that the left border of the syn-alert reaches the edges again

fix: 🐛 syn-alert's left border does not reach the edge anymore

---

.github/workflows/chromatic-main.yml
.github/workflows/publish-docs.yml
.github/workflows/quality-check.yml
.github/workflows/release.yml

This PR fixes our github actions.
Our `deploy-docs` actions needs an explicit pnpm version added, as the package.json key "packageManager" is not available there.
Also we updated the supported node version to be ">=20.0.0", which lead to warning in some actions as there node 18 was used
Have a look at the github actions and verify that there is no issue / warning anymore

chore: 🔧 Fix github actions

---

packages/components/src/components/nav-item/nav-item.component.ts
packages/components/src/components/nav-item/nav-item.test.ts
packages/components/src/components/side-nav/side-nav.test.ts

This PR fixes the issue that in firefox the syn-side-nav with nested syn-nav-items does not show an indentation for them.
Closes #708 
This problem occurs only in firefox. 
Using `getComputedStyles` in firefox with a parent window with no presentation (e.g. display: none) results in an empty object. For more information about this see [the firefox notes on caniuse](https://caniuse.com/?search=getComputedStyle).
Nesting the syn-nav-items without an syn-side-nav works fine in firefox, but our syn-side-nav uses a syn-drawer in itself, which leads to this behavior. It has nothing to do with the side-nav or the drawer but just the fact of slotting the nav-item into a custom-element which uses a custom element in it. This seems to trigger the behavior in firefox only.
My guess would be that the …

fix: 🐛 Indentation of nested nav-items in side-nav is not shown correctly for firefox

---

packages/components/scripts/vendorism/custom/option.vendorism.js
packages/components/scripts/vendorism/custom/webTestRunner.vendorism.js
packages/components/src/components/combobox/combobox.component.ts
packages/components/src/components/combobox/combobox.custom.styles.ts
packages/components/src/components/combobox/combobox.test.ts
packages/components/src/components/combobox/option-renderer.ts
packages/components/src/components/combobox/utils.ts
packages/components/src/components/optgroup/optgroup.styles.ts
packages/components/src/components/option/option.component.ts
packages/components/src/components/option/option.custom.styles.ts
packages/components/web-test-runner.config.js

This PR fixes multiple issues with the syn-combobox:
- syn-option's do not honor applied styles 
- syn-optgroup not working correctly (e.g. no slot is working, the label property in react)
- toggling open state with the expand icon not always working correctly
the first two issues are fixed by no longer cloning the syn-options and working with the clones, but just working with the syn-options themselves.
Additionally this PR fixes a performance issue, which was added via shoelace update in the syn-option.
Closes #719 , #712, #714 
When using the combobox within a [MUI dialog](https://mui.com/material-ui/react-dialog/) the open state can now be toggled correctly via expand icon:
To test this install MUI in the react demo application: 
```
pnpm add @mui/material @emotion/react …
```

fix: 🐛 Various issues with syn-combobox

---

packages/angular/src/components/side-nav.component.ts
packages/components/src/components/side-nav/side-nav.component.ts
packages/components/src/components/side-nav/side-nav.styles.ts
packages/react/src/components/side-nav.ts
packages/react/src/types/syn-jsx-elements.ts
packages/vue/src/components/SynVueSideNav.vue

This PR fixes an issue of the rendering order with syn-side-nav in rail mode and main content with a higher z-index.
Additionally it exports all necessary drawer css parts
Closes #736 
Add this code to the side-nav story in the main content area and see that the text is no longer shown above the expanded side-nav:
``` html
<div style="position:absolute; z-index:10; margin-top:100px;">some text with higher z-index</div>
```

fix: 🐛 Z-index order rendering problem with syn-side-nav in rail mode

---

packages/components/src/components/checkbox/checkbox.custom.styles.ts

This PR fixes the wrong label color on disabled `<syn-checkbox>` to make it align with `<syn-switch>` and `<syn-radio>`.
Closes #734
I don´t quite know anymore why we put it there in the first place, but we have overridden the `disabled` state on purpose during the initial vendoring process. Maybe the token was not there initially?
Just have a look at the disabled Story of `<yn-checkbox>` in Chromatic. Also, compare this to the version for `<syn-switch>` and `<syn-radio>`.

fix: 🐛 Checkbox and Radio have different disabled styles

---

packages/components/src/components/side-nav/side-nav.component.ts

Currently our side-nav does not work correctly for specific production builds ( e.g. angular with specific production settings). Until know the actual problem is unknown..
Adding the eventlisteners for the side nav directly on the drawer instead of the side-nav itself so it uses bubbled events, fixes the problem.
Closes #743 
Can currently only be reproduced in medici-ng project

fix: 🐛 Side-nav not working correctly for some production builds

---

packages/components/src/components/validate/validate.component.ts
packages/components/src/components/validate/validate.test.ts

This PR fixes an issue with `<syn-validate>` which lead to a visualization problem when setting or removing `disabled` or `readonly` properties on the slotted input field. If rendered with one of those properties initially and eager set, the validation would not show an error message when the property was removed later on.
Closes #717
Code-wise, I had to use `Element.getAttribute` instead of simple checks like `element.disabled`. This is because Shoelace uses other props than regular html (e.g. `readOnly` instead of `readonly`). As attributes are case insensitive, this lead to easier checks.
I opted to setup the needed `MutationObserver` on `connectedCallback` on the element itself. This was done to make sure that the observer always listens to changed nodes and also picks up complete new …

fix: 🐛 syn-validate: Validation message not removed when the slotted input is set to readonly or disabled

---

packages/components/src/components/validate/validate.component.ts
packages/components/src/components/validate/validate.test.ts

This PR fixes an issue when using `<syn-validate>` with a `custom-error-message` and `eager` loading. In this combination, there was no error message shown when the native constraint validation API was not kicking in.
This can be best viewed at [the corresponding codepen](https://codepen.io/schilchSICKAG/pen/RNbYrpr?editors=1110). As can be seen, the validation triggers on the first example, but not on the second one.
The reason for this is that we do not a initial set of the `customValidationMessage` of the internal input before doing our eager check. This is now fixed with this PR.
Closes #713
I opted to include the test in `firstUpdated` directly so I did not have to mess with changing `handleCustomValidationMessageChange` to trigger another validation run. I found this to be easier to …

fix: 🐛 syn-validate: Rendered input should be highlighted as error when loading with an invalid state

---

packages/angular/src/components/range.component.ts
packages/components/scripts/jobs/shared.js
packages/components/scripts/jobs/vue/createWrappers.js
packages/components/src/components/range/range.component.ts
packages/components/src/components/range/range.styles.ts
packages/components/src/components/range/range.test.ts
packages/vue/src/components/SynVueCheckbox.vue
packages/vue/src/components/SynVueCombobox.vue
packages/vue/src/components/SynVueFile.vue
packages/vue/src/components/SynVueInput.vue
packages/vue/src/components/SynVueRadioGroup.vue
packages/vue/src/components/SynVueRange.vue
packages/vue/src/components/SynVueSelect.vue
packages/vue/src/components/SynVueSwitch.vue
packages/vue/src/components/SynVueTextarea.vue

This PR fixes a couple of issues reported for `<syn-range>`. As usual, I will provide information about the fixes step by step.
Closes #741 (Umbrella for tickets below)
Closes #727
Closes #728
Closes #729
Closes #595
All in all those where pretty easy changes that don´t seem to break anything. Just have a look at the current version and compare the the latest main. I tried to keep the commits clean per feature (which didn´t completely work out ^^), but it should give you an idea what was changed and why.
This was a funny one. When using `<syn-range>` with ticks and slots, it drew the slotted prefix and suffix icons on the same level as the tick. This **only happens** when the ticks have a height reported as `0`. This may happen in the following case (can also be used to test it):
```html …
```

fix: 🐛 syn-range Various issues for syn-range

---

packages/components/src/components/side-nav/side-nav.component.ts

This PR removes an accessibility error, which potentially occurs in the console if using the syn-side-nav.
It is related to an error in the drawer (even in shoelace see https://github.com/shoelace-style/shoelace/issues/2283 )
Closes #750

fix: 🐛 Accessibility error in console when using syn-side-nav as rail

---

packages/components/scripts/jobs/react/intrinsic-elements.js
packages/react/src/types/syn-jsx-elements.ts

This PR fixes two issues with our new type only react support. IT addresses the following issues:
- `ref` was not a supported property on the wrappers, making it impossible to use `useRef()` with TypeScript
- The generic `styles` property in React does not support css custom properties.
Closes #746
I was slightly tempered to only include our Synergy Tokens in the allowance list, which would have forced their usage. However, I think as we don´t quite know what other component libraries are used by our customers, I went with a dynamic key in `interface CSSProperties`.
Just check out this branch and play around with the react demo. The following code will throw typescript errors:
```jsx
// DemoForm.tsx
import { useRef, useEffect } from 'react';
export const DemoForm = () => {
// Try to …
```

fix: 🐛 React: style and ref for react19 not working

---

packages/components/src/components/combobox/combobox.component.ts
packages/components/src/components/header/header.component.ts

This PR removes the console warning messages of the syn-header and syn-combobox with value.
The warning appears, because changes are done in the `firstUpdated` callback, which lead to updated changes. By waiting for `this.updateComplete` before doing the changes, they are no longer triggering during the update process.
Closes #753 
Have a look at any syn-header story and check following code for the syn-combobox, that there is no longer this warning message in the console
```html
<syn-combobox value="opt1">
<syn-option value="opt1">Option 1</syn-option>
<syn-option value="opt2">Option 2</syn-option>
<syn-option value="opt3">Option 3</syn-option>
</syn-combobox>
```
Unfortunately there is no way I can test this via unit test 😕
Or at least I have no idea how I could test it

fix: 🐛 Remove warning message in console for syn-header and syn-combobox in dev mode

---

packages/components/src/components/input/input.custom.styles.ts

Currently we add a fix min-width for ALL syn-inputs. The min-width was only meant for type="number" with displayed spin buttons, so there is always a number visible.
Closes #755 
Unfortunately it is not possible to use something like **2em** or **2rem** for the min-width as the min-width refers to the whole with of the syn-input and not only the `<input/>` element.
Check out that following code will no longer restrict ALL syn-inputs to the min-width but only the `<syn-input type="number" />`
```html
<syn-input type="email" placeholder="Email"></syn-input><br/>
<syn-input type="number" placeholder="Number" size="small"></syn-input><br/>
<syn-input type="number" placeholder="Number"></syn-input><br/>
<syn-input type="number" placeholder="Number" size="large"></syn-input><br/>
<syn-input …
```

fix: 🐛 Only apply min-width styling for syn-input type="number" with spin buttons

---

packages/components/src/components/input/input.custom.styles.ts

Using the syn-input in a flex or grid container leads to overflowing of it over the container.
This PR fixes this issue.
Closes #761 
Check out this code, if the syn-input now no longer overflows with the fix: 
```html
<div class="flex">
<syn-input></syn-input>
<syn-input></syn-input>
</div> 
<div class="grid">
<syn-input></syn-input>
<syn-input></syn-input>
<syn-input></syn-input>
<syn-input></syn-input>
</div> 
<style>
.flex {
display: flex;
gap: 8px;
width: 200px;
border: 2px solid red;
margin-bottom: 24px;
}
.grid {
border: 2px solid red;
display: grid;
grid-template-columns: 1fr 1fr;
grid-gap: 8px;
width: 200px;
}
syn-input {
min-width: unset;
}
</style>
```

fix: 🐛 syn-input is overflowing in flex and grid container with fix size

---

packages/styles/build/jobs/postcss.js

This PR adds some fixes for synergy not building on Windows. Cause of the problem was that [getDistName](https://github.com/synergy-design-system/synergy-design-system/blob/main/packages/styles/build/jobs/postcss.js#L15) did not check for proper filesystem variants, making it unable to create the file bundles in the first place.
Closes #785 
-
Just check out this branch and check if you can build the `styles` package on Windows now.

chore: 🔧 styles: Make build run on Windows

---

packages/components/scripts/vendorism/custom/select.vendorism.js
packages/components/src/components/select/select.component.ts
packages/components/src/components/select/select.custom.test.ts

This PR fixes the issues described in #780. It does so by adjusting the setter for `value` in case of `multiple` is set to true.
Closes #780 
I opted to allow non falsy values, too, so a value of `1` (Number) will result in `[1]`. However, falsy values will be removed, e.g. a value of `undefined` or `false` will `[]`. 
```javascript
// Test script
const sel = document.querySelector('syn-select')
sel.multiple = true;
sel.value = false;
console.log(sel.value);
```
1. Open https://synergy-design-system.github.io/iframe.html?globals=viewport%3AdefaultViewPort&args=&id=components-syn-select--multiple&viewMode=story
2. Run the code displayed above in the console. See that there is an error `t.split is not a function`.
3. Run the same with the code changes in this PR (e.g. on Chromatic …

fix: 🐛 syn-select with multiple should not error when value is set to a falsy value

---

packages/components/src/components/card/card.custom.styles.ts

This problem fixes the issue, that if wrapping the slot content of a syn-card with another html tag (like `<span/>`) the font-size and color of the content in the syn-card can not be changed.
Closes #789 
There should be no change for the stakeholder with this fix. They would need to overwrite the syn-card::part(body) explicitly to change their content font-size in the syn-card.
Use this test code. Before only the background was applied, but not the color and font-size styling. With the fix now every stylings are applied
```html
<syn-card class="card-basic">
<span>
This is just a basic card. No image, no header, and no footer. Just your content.
</span>
</syn-card>
<style>
syn-card::part(body) {
background:green; /* is getting applied */
color:red; /* is NOT getting applied */
font-size: …
```

fix: 🐛  syn-card font-size and color of slot content can not be changed 

---

packages/components/src/components/input/input.custom.test.ts
packages/components/src/internal/longpress.test.ts
packages/components/src/internal/longpress.ts

This PR fixes the issue that if a `<syn-input type="number"/>` was removed from DOM but appended again, the stepper buttons would no longer work. This is because the `longpress` directive would remove the eventlistener and not append it again, as the directive is not completely new created but RECONNECTED.  Therefore the eventlistener is attached again, if the `reconnected` lifecycle method of the directive is called.
Closes #795 
Unfortunately I needed to add some test to the syn-input itself as for some reason I was not able to trigger the `disconnected` method of the directive in their unit tests 😕
Check out this code if it is working now: 
```html
<div id="wrapper">
<syn-input id="input" type="number" placeholder="Number"></syn-input>
<syn-button id="btn">btn</syn-button>
</div> …
```

fix: 🐛 stepper buttons of reused syn-input type=number node no longer working

---

packages/components/src/utilities/defaultSettings/decorator.ts
packages/components/src/utilities/defaultSettings/defaultSettings.test.ts

This PR fixes the issue, that explicitly set properties with their default value (e.g. size="medium" for the syn-button `<syn-button size="medium" />`) is not honored, but overwritten with the new default value.
Closes #799 
I just found out that the `requestUpdate` callback is called for explicitly set properties, even if the property is set to its default value. If a property is not explicitly set, this callback is not called. This behaves the same for plain webcomponents and for all 3 web frameworks.
Via this mechanism we can find out, if just the default from internal was used or if it was explicitly set.
- check out for plain web component and all 3 web frameworks, if the behavior is now correct!
- example code angular: 
```html
<syn-button>default</syn-button>
<syn-button …
```

fix: 🐛 setGlobalDefaultSettings does overwrite explicitly set default property values with new default size

---

packages/angular/components/input/input.component.ts
packages/components/scripts/vendorism/custom/input.vendorism.js
packages/components/src/components/input/input.component.ts
packages/components/src/components/input/input.styles.ts
packages/react/src/components/input.ts
packages/react/src/types/syn-jsx-elements.ts
packages/vue/src/components/SynVueInput.vue

This PR adds the possibility to adjust the default coloring of `<syn-input>` when used with user data autofilling enabled.
Closes #800 
Autofill has some common requirements:
1. You need to have it wrapped in a form
2. You have to have at least two fields for autocomplete to work (e.g. E-Mail and Name, Street...)
3. Your browser must be setup to automatically add your contact information (default for Safari, configurable for the other browsers)
Start Storybook and add the following story to `input.stories.ts`:
```typescript
export const FormDemo: Story = {
render: () => html`
<form method="post">
<syn-input name="name" type="text" label="Name"></syn-input>
<syn-input name="street" type="text" label="Street"></syn-input>
<syn-input name="email" type="email" label="E-Mail"></syn-input> …
```

feat: ✨ Allow to override autofill styles for syn-input

---

packages/angular/components/details/details.component.ts
packages/components/scripts/vendorism/custom/details.vendorism.js
packages/components/src/components/details/details.component.ts
packages/react/src/components/details.ts
packages/react/src/types/syn-jsx-elements.ts
packages/vue/src/components/SynVueDetails.vue

This PR adds a new part `body` that can be used to style the wrapper that holds the default slotted content of a `<syn-detail>` element.
Closes #811
Regular vendoring process.
Just play around with the generated storybook and add some color to it.

feat: ✨ syn-details exports content_wrapper as CSS part

---

packages/angular/components/nav-item/nav-item.component.ts
packages/components/src/components/nav-item/nav-item.component.ts
packages/components/src/components/nav-item/nav-item.test.ts
packages/vue/src/components/SynVueNavItem.vue

This PR adds the new `target` and `rel` properties as they are currently defined in `<syn-button>` for `<syn-nav-item>`.
Closes #779
I just ported both properties, together with their logic. Nothing fancy here.
Other than playing around with it in Storybook, there is really nothing to do here.

feat: ✨ syn-nav-item: Allow opening links in new windows

---

packages/_private/angular-demo/src/AllComponentParts/Combobox.ts
packages/_private/angular-demo/src/AllComponentParts/Select.ts
packages/_private/e2e-demo-test/src/AllComponents.spec.ts
packages/_private/e2e-demo-test/src/test.selector.ts
packages/_private/react-demo/src/AllComponentParts/Combobox.tsx
packages/_private/react-demo/src/AllComponentParts/Select.tsx
packages/_private/vanilla-demo/src/AllComponentParts/Combobox.ts
packages/_private/vanilla-demo/src/AllComponentParts/Dialog.ts
packages/_private/vanilla-demo/src/AllComponentParts/Select.ts
packages/_private/vanilla-demo/src/all-components-regressions.ts
packages/_private/vanilla-demo/src/all-components.ts
packages/_private/vue-demo/src/AllComponentParts/DemoCombobox.vue
packages/_private/vue-demo/src/AllComponentParts/DemoSelect.vue
packages/components/scripts/vendorism/custom/select.vendorism.js
packages/components/src/components/combobox/combobox.component.ts
packages/components/src/components/combobox/combobox.test.ts
packages/components/src/components/select/select.component.ts
packages/components/src/components/select/select.custom.test.ts

This PR fixes problems, when the value of syn-select or syn-combobox was initially set via property binding. 
Closes #813 
The `defaultValue` of the combobox and select is used for setting the new value of the component on slotChange event or if resetting the component value in a form.
But the mechanism behind `defaultValue` was only working if the value was set via attribute binding but not for property binding!
It just came to my mind, that we should check all the other form elements... not just select and combobox.
I will have a look into it.
For the frameworks have a look at the `combobox` and `select` parts of the `AllComponents` section.
For storybook use following code snippets.
```js
export const SelectBug: Story = {
parameters: {
docs: {
description: {
story: …
```

fix: 🐛 Combobox and select not working correctly if value was initially set via property binding

---

packages/_private/angular-demo/src/AllComponentParts/TabGroup.ts
packages/_private/e2e-demo-test/src/AllComponents.spec.ts
packages/_private/e2e-demo-test/src/test.selector.ts
packages/_private/react-demo/src/AllComponentParts/TabGroup.tsx
packages/_private/vanilla-demo/src/AllComponentParts/TabGroup.ts
packages/_private/vanilla-demo/src/all-components-regressions.ts
packages/_private/vue-demo/src/AllComponentParts/DemoTabGroup.vue
packages/components/scripts/vendorism/custom/tab-group.vendorism.js
packages/components/src/components/tab-group/tab-group.component.ts

This PR fixes the problem, that if a new active tab and panel `<syn-tab active />` is added in an angular project, the new panel content is not shown. Instead no panel content at all is shown.
This problem seems to be only appearing with angular, because it handles some timings / lifecycles different than the other frameworks.
Shoelace caches all tab-panels and tabs e.g. on slotchange. But for angular this is not enough. For this bug, the slotchange fires too late.
To fix this problem I decided to no longer cache the tabs and panel but just use the `@queryAssignedElements`
Closes #814 
Example code to test this behavior:
```typescript
import { Component } from '@angular/core';
@Component({
selector: 'home',
standalone: false,
template: `
<syn-tab-group contained>
@for (item of items; …
```

fix: 🐛 dynamically added active tab in angular does not show any panel content

---

packages/components/src/components/range/range.component.ts
packages/components/src/components/range/range.styles.ts
packages/components/src/components/range/range.test.ts

This PR adjusts the layout of `<syn-range>`. This is done to prevent the thumb from being drawn outside of the visible area.
Closes #809 
I just had to add some internal spacing, both negative and positive ones, depending on the element. I added a new internal token named `--half-thumb-size` as the half size of the thumb is now used on at least 3 different places in the code. All original occurrences have been moved to this new token.
Have a look at the storybook stories for a visual representation. Notice that the track is still starting on the start of the element, but the know will now happily move to the edge of the visual space when hitting both the left and right boundaries instead of moving over them. This also works when having a prefix or suffix.

feat: ✨ syn-range should align vertically with other input elements

---

packages/components/scripts/vendorism/custom/select.vendorism.js
packages/components/src/components/select/select.component.ts

This PR makes the syn-select more robust. 
Closes #845 
Check that following code no longer leads to an error in the console:
```html
<syn-select .value=${undefined}> </syn-select>
```

fix: 🐛 Make the syn-select more robust to allow undefined as value

---

packages/components/src/components/input/input.custom.styles.ts
packages/components/src/styles/form-control.custom.styles.ts

This PR fixes some non-alignment of inner paddings with design.
Non alignment appears if:
- having only a suffix slot
- having clearable property set
- having password-toggle set
Closes #817.
Example code for testing:
```html
<syn-input label="Correct right padding" value="aaaasadasdjasdasdasdasdasdasdasdasdasdasdsdsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf">
<span slot="prefix">prefix</span>
<span slot="suffix">suffix</span>
</syn-input>
<syn-input label="Incorrect right padding" value="aaaasadasdjasdasdasdasdasdasdasdasdasdasdsdsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdf">
<span slot="suffix">suffix</span>
</syn-input>
<syn-input clearable label="Incorrect right padding" value="aaaasadasdjasdasdasdasdasdasdasdasdasdasdsdsdfsdfsdfsdfsdfsdfsdfsdfsdf …
```

fix: 🐛 syn-input has some paddings which are not aligned with design

---

packages/components/src/components/tooltip/tooltip.custom.styles.ts

This PR adds a fix for `<syn-tooltip>` that made coloring harder. The root cause was that the provided `box-shadow` on the body of the `<syn-tooltip>` was positioned **above** the `arrow`, which made it look wrong in all but very dark backgrounds (like Synergies default).
Closes #640 
I also tried experimenting with replacing the `box-shadow` with a `filter: drop-shadow` on the underlying `<syn-popup>`. This works fine for the most part, however our variables are not able to be used with this, so I left it. Maybe this is something we can adjust in a future major version.
Just set the color of a given tooltip via `--syn-tooltip-background-color` to `red` in current Storybook. You will notice the color is bleeding over the arrow. Do the same in the created storybook. You will notice that …

fix: 🐛 syn-tooltip - box-shadow bleeds into tooltip arrow

---

packages/angular/components/combobox/combobox.component.ts
packages/angular/components/select/select.component.ts
packages/components/scripts/vendorism/custom/select.vendorism.js
packages/components/src/components/combobox/combobox.component.ts
packages/components/src/components/select/select.component.ts
packages/react/src/components/combobox.ts
packages/react/src/components/select.ts
packages/react/src/types/syn-jsx-elements.ts
packages/vue/src/components/SynVueCombobox.vue
packages/vue/src/components/SynVueSelect.vue

This PR provides changes that make it possible to override the width of the `syn-popup` used in `<syn-select>` and `<syn-combobox>`
Closes #781 
I went with the approach of defining a default behavior. After testing in Storybook and the demo projects, there seems nothing breaking in there.
Use @kirchsuSICKAG example from the ticket in Storybook to test:
```html
<div class="container">
<syn-select label="Option more lines">
<syn-option value="option-1">This is a long text exceeding the input width</syn-option>
<syn-option value="option-2">This is a long text exceeding the input width</syn-option>
<syn-option value="option-3">This is a long text exceeding the input width</syn-option>
</syn-select>
<syn-select class="one-line"  label="Option one line">
<syn-option value="option-1">This is a …
```

feat: ✨ syn-combobox, syn-select: Allow listbox of syn-select to exceed the input width

---

packages/components/src/components/header/header.component.ts

This PR fixes an issue with `<syn-header>` that lead to animation issues when clicking the burger menu icon too fast.
Closes #587
I just added a small status variable to check if the animation of the linked `<syn-side-nav>` is already finished. If it is not, the click on the item will do nothing.
I was also thinking about adding something like a `cursor: wait;` to the item in this case, but did not want to make the private property reactive, which would have caused rerenders on finish. Would be possible by using `@state isSideNavAnimating` instead of a private variable.
Just click the burger menu icon as fast as you can :). It should break in our current implementation, but ignore the subsequent clicks and not toggle the icon when the animation takes place.

fix: 🐛 syn-side-nav does not correctly reappear after double-click on burger menu

---

packages/components/LIMITATIONS.md

This PR adds more documentation to using `syn-hide` events in `<syn-dialog>` elements.
Closes #572
As this was already documented, I just rewrote and added the items that may affect this behavior.
Just have a look at the created storybook and read the components limitation file adjustments.

docs: 📚 Known limitations: Clarify using syn-hide events in dialogs

---

packages/_private/angular-demo/src/AllComponentParts/Select.ts
packages/_private/e2e-demo-test/src/AllComponents.spec.ts
packages/_private/e2e-demo-test/src/test.selector.ts
packages/_private/react-demo/src/AllComponentParts/Select.tsx
packages/_private/vanilla-demo/src/AllComponentParts/Select.ts
packages/_private/vanilla-demo/src/all-components-regressions.ts
packages/_private/vue-demo/src/AllComponentParts/DemoSelect.vue
packages/components/scripts/vendorism/custom/select.vendorism.js
packages/components/src/components/select/select.component.ts
packages/components/src/components/select/select.custom.test.ts
packages/components/src/components/select/utility.ts

This PR fixes an issue, which only appears with angular with specific circumstances. 
If using a syn-select:
- with multiple
- async options
- normal `value` binding
```html
<syn-select multiple value="1 2" >
@for (option of asyncOptions; track $index; let index = $index) {
<syn-option [value]="option.value">{{option.label}}</syn-option>
}
</syn-select>
```
Closes #851 
We had two failures parts in the syn-select. But these parts seems to only occur with angular and are "fixed" (overwritten) if used with any other framework.
At one point two arrays where compared but it was false every time because `['1'] === ['1']` is always false. Therefore I added a compareValues utility function, which checks if the arrays are the same.
At another part we checked if an value is an array and if not we …

fix: 🐛  Angular problem with multiple select and async options

---

packages/_private/angular-demo/src/AllComponentParts/Select.ts
packages/_private/e2e-demo-test/src/AllComponents/SynSelect.spec.ts
packages/_private/e2e-demo-test/src/test.selector.ts
packages/_private/react-demo/src/AllComponentParts/Select.tsx
packages/_private/vanilla-demo/src/AllComponentParts/Select.ts
packages/_private/vue-demo/src/AllComponentParts/DemoSelect.vue
packages/components/scripts/vendorism/custom/select.vendorism.js
packages/components/src/components/select/select.component.ts
packages/components/src/components/select/utility.ts

This PR fixes an issue when using `<syn-select>` with numeric zero values. This was caused by using a `Boolean` filter on arrays that mistreats `0` as `false` when cast via `Boolean(0)`.
Closes #885
Just have a look at the code changes, they are quite minimal. I opted to reuse the already existing `isAllowedValue` function.
Create `<syn-select>` with various values in the demo applications or storybook. The following code (taken from react) shows the example:
```tsx
const MyTest = () => (
<syn-select
data-testid="select-885-value-zero-number"
label="Select should allow to select value of number(zero)"
value={0}
>
<syn-option value={0}>Zero (numeric)</syn-option>
</syn-select>
);
```
This will not select the given option. With the fix applied, the option will be selected.

fix: 🐛 syn-select with numeric value does not work with 0

---

packages/components/scripts/vendorism/custom/select.vendorism.js
packages/components/src/components/select/select.test.ts
packages/docs/src/shared-components/IconSearchPage.tsx
packages/docs/stories/IconSearch.mdx

With the turbosnap merge and the needed changes there in storybook, the Icon Search was broken and did no longer show the icons.
The icons where no longer imported in the `preview.ts`. So for the icon search "another" synergy components version was used, because only the react icon component was imported. So the react-icon used the bundled synergy version and not the package itself. Therefore the registerIconLibrary was done for another synergy build.

chore: 🔧 fix icon search not showing icons anymore

---

packages/_private/angular-demo/src/AllComponentParts/Validate.ts
packages/_private/e2e-demo-test/src/AllComponents/SynValidate.spec.ts
packages/_private/e2e-demo-test/src/test.selector.ts
packages/_private/react-demo/src/AllComponentParts/Validate.tsx
packages/_private/vanilla-demo/src/AllComponentParts/Validate.ts
packages/_private/vanilla-demo/src/all-components-regressions.ts
packages/_private/vue-demo/src/AllComponentParts/DemoValidate.vue
packages/components/src/components/validate/validate.component.ts
packages/components/src/components/validate/validate.test.ts
pnpm-workspace.yaml

This PR fixes the problem, that potentially the form element is not shown with red border, if a custom event for the `on` property is used.
Closes #915 
Have a look at the demo pages and tests.

fix: 🐛 syn-validate - Incorrect state of form element if setting customValidationMessage via custom event

---

packages/_private/angular-demo/src/app.component.html
packages/_private/e2e-demo-test/src/AppShell.spec.ts
packages/_private/e2e-demo-test/src/PageObjects/AllComponents.ts
packages/_private/e2e-demo-test/src/PageObjects/AppShell.ts
packages/_private/e2e-demo-test/src/PageObjects/PageObject.ts
packages/_private/e2e-demo-test/src/PageObjects/index.ts
packages/_private/e2e-demo-test/src/test.selector.ts
packages/_private/react-demo/src/Layout.tsx
packages/_private/vanilla-demo/src/layout.ts
packages/_private/vue-demo/src/App.vue
packages/components/src/components/header/header.component.ts

This PR fixes an issue with a specific combination of `<syn-header>` and `<syn-side-nav>` when using the `default` value for `<syn-side-nav>`'s `variant`.
The issue is caused by a side effect of #587. We opted to check for the `<syn-side-nav>`'s `syn-hide` and `syn-show` events to check if it is still animating. However, nested `<syn-nav-item>` elements **also emit** the same events when opened or closed. As this [was not scoped in our code](https://github.com/synergy-design-system/synergy-design-system/blob/main/packages/components/src/components/header/header.component.ts#L173), the header set its `isAnimating` property to true when the `<syn-nav-item>` was toggeled to open state.
This is now fixed by checking the root element of the event that is emitted. We now only toggle the …

fix: 🐛 syn-header with syn-side-nav burger menu stops working
