packages/assets/package.json
packages/components/package.json
packages/tokens/package.json

This PR concerns missing jobs in the current CI/CD setup -> the *"release"* script was added to the packages "assets", "tokens" and "components". 
Furthermore, the possibility to switch from "npm publish" to "pnpm publish" is being considered.
* The current CI/CD setup does not work as there are missing jobs
To check if the CI/CD is now working, this PR was created, to test the deployment and its success.

chore: 🔧 fix Semantic Release on CI/CD

---

packages/assets/package.json
packages/components/package.json
packages/tokens/package.json
pnpm-lock.yaml

The semantic-release version wasn't compatible with the semantic-release-monorepo and a "release-fallback" branch was neccessary in the configuration.
* The release was not successful due to the issues described above.
These were the results from the previous release that failed, so you can see the errors: https://github.com/SickDesignSystem/synergy/actions/runs/6585242049/job/17891283869 
This PR is the only way to test this functionality.

chore: 🔧 fix Semantic Release version on CI/CD 

---

packages/tokens/src/figma-tokens/_docs.json

docs: input tokens

---

packages/docs/package.json
pnpm-lock.yaml

There were some unneeded dependencies for Chromatic. This PR removes them.

chore: remove unneeded packages

---

packages/components/scripts/vendorism.js
packages/components/src/components/input/input.custom.styles.ts
packages/components/src/components/input/input.styles.ts

chore: inject custom styles in vendored components

---

.github/workflows/release.yml
packages/components/package.json
packages/tokens/package.json

1. Run semantic release for all relevant packages
2. prepare all packages via exec
3. exec will update react package as well
4. let check pnpm what's going to be published

chore: fix release

---

packages/components/package.json
packages/tokens/package.json
pnpm-lock.yaml

This PR adds the missing dev-dependencies to make automatically releases work.

chore: fix release (add missing devDependencies)

---

packages/components/package.json
packages/tokens/package.json
pnpm-lock.yaml

The order of semantic-version scripts is not right, also it does not include all react package when creating new versions.

chore: fix release (reorder of script steps)

---

packages/tokens/src/figma-tokens/$themes.json
packages/tokens/src/figma-tokens/semantic/input.json

feat: update input-tokens

---

.github/workflows/publish-docs.yml

docs: publish docs on github pages (closes #102)

---

packages/tokens/src/figma-tokens/$metadata.json
packages/tokens/src/figma-tokens/_docs.json
packages/tokens/src/figma-tokens/button.json

feat: ✨ add button tokens

---

packages/tokens/src/figma-tokens/semantic/input.json

fix-input-tokens-spacing

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 syn-button docs tokens

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 syn-textarea docs tokens

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 add docs for syn-switch

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 fix filled text into read-only text

---

packages/tokens/src/figma-tokens/$themes.json
packages/tokens/src/figma-tokens/_docs.json

docs: 📚 button 'filled' wording

---

packages/components/README.md

This PR adds information about how to use VSCode autocompletion for projects that are using our components.
Closes #44.
Just have a look at the new [README.md](https://github.com/SickDesignSystem/synergy/blob/docs/autocompletion-in-HTML/packages/components/README.md#5-add-html-autocompletion-to-vscode-optional) for components
- Create a new, empty project (e.g. via `npm init`).
- Install our components package `npm install --save @synergy-design-system/components@main`).
- Proceed like described in the new README.md.
- Create a new file `index.html`
- You should now get autocomplete when typing `<syn` for `syn-button` and `syn-input`

docs: 📚 Autocompletion in HTML

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 add docs for invalid and focus states

---

packages/tokens/src/figma-tokens/semantic/focus-ring.json

fix: 🐛 use correct focus ring width

---

.github/workflows/lint-pr-title

The PR title is used as a default for Squash Commits. As I manually renamed our PR titles the last times, I want a check, that does it automatically, that it fits to Semantic Release (or not).

chore: 🔧 add PR title linter

---

.github/workflows/lint-pr-title.yml

chore: 🔧 Update and rename lint-pr-title to lint-pr-title.yml

---

.github/workflows/lint-pr-title.yml

chore: 🔧 Update lint-pr-title.yml

---

.github/ISSUE_TEMPLATE/component-request-feature.md
.github/ISSUE_TEMPLATE/component-request-new-component.md
.github/ISSUE_TEMPLATE/generic-bug.md
.github/ISSUE_TEMPLATE/generic-feature.md
.github/pull_request_template.md

- Based on the discussions we had recently I did a few modifications to the issue templated
- Added a new section (Acceptance criteria)
- Made clear that the Checklist is for the issue creator
no issue 🙈

docs: 📚 Added acceptance criteria to issue templates

---

packages/_private/angular-demo/angular.json
packages/_private/angular-demo/package.json
packages/_private/angular-demo/src/app/app.component.html
packages/angular/README.md
packages/angular/package.json
packages/react/package.json
pnpm-lock.yaml

This PR fixes an issue with semver ranges in `@synergy-design-system/angular` and `@synergy-design-system/react` that used to ship their `dependencies` and `peerDependencies` with fixed release numbers for `@synergy-design-system/components`. This lead to an error during installation via npm.
It also includes an update for `@synergy-design-system/angular` that adds compatibility with Angular@17.
Closes #172.
Have a look at the wrappers `package.json` files. Both now use the `^` symbol for the workspace links. This means a publish will use `@synergy-design-system/components: "^1.x.x"`, allowing all packages in the 1.x range, instead of `@synergy-design-system/components: "1.x.x"` as a fixed dependency as before.
- Issue `pnpm i -r && pnpm build`
- Move to …

fix: 🤔 Angular and React use fixed dependency versions instead of semver range

---

packages/tokens/src/figma-tokens/_docs.json

Problem with the Docs Tokens should be fixed now

docs: 📚 Radio docs tokens

---

packages/tokens/package.json
packages/tokens/scripts/outputs/js.js
pnpm-lock.yaml

This PR adds the missing ts types which lead to warnings in ts projects that try to load the javascript exports from `@synergy-design-system/tokens`.
Closes #178
- I have opted to create the types without using `tsc` to still have a smaller boilerplate.
- Only the `js.js` build format needed to be adjusted for this, no other dependencies where necessairy.
- Make sure to run `pnpm install -r && pnpm build`
- Have a look at `packages/docs/dist/js/`. The folder should now include a `index.js` and `index.d.ts` file.
- The `package.json` for tokens includes a `types` and `exports.default.types` field.
- Add the following line to the react demo (located at `_private/react-demo/src/main.ts`): `import * from '@synergy-design-system/tokens`). There should be no "types not …

feat: ✨ Add types for @synergy-design-system/tokens

---

packages/angular/README.md
packages/angular/src/modules/forms.module.ts
packages/components/package.json
packages/components/scripts/jobs/angular/createFormsModule.js

This PR fixes the problem, that not all angular wrapper components participate in form data.
Closes #195 
Closes #189 
Go into the angular-demo (_private/angular-demo) and run pnpm start

fix: 🤔 Make all angular wrapper participate in form data

---

.github/workflows/publish-docs.yml

chore: use git for github pages deployment

---

packages/assets/CHANGELOG.md
packages/components/CHANGELOG.md
packages/tokens/CHANGELOG.md

fix: improve changelogs

---

packages/docs/stories/components/button.stories.ts
packages/docs/stories/components/radio-group.stories.ts
packages/docs/stories/components/radio.stories.ts
packages/docs/stories/components/switch.stories.ts
packages/docs/stories/components/textarea.stories.ts

This pull request fixes the documentation for the storybook components. The descriptions for the components 'button', 'radio-group', 'radio', 'switch', and 'textarea' have been updated to provide more accurate information. This will improve the user experience and make it easier for developers to understand and use these components effectively.

docs: 📚 fix storybook documentation

---

CONTRIBUTING.md
cspell.json
packages/components/package.json
packages/docs/.storybook/main.ts
packages/docs/stories/Contributing.mdx
packages/docs/stories/Index.mdx
packages/docs/stories/Introduction.mdx

Revised contribution guidelines and added to storybook.
https://github.com/synergy-design-system/Internal/issues/51

docs: 📚 improve contribution guidelines

---

packages/components/package.json
patches/semantic-release-monorepo@7.0.5.patch
pnpm-lock.yaml

Re-adds GitHub in release process of components and makes script semantic-release-monorepo work if there are no dependencies set.

chore: 🔧 fix release

---

CONTRIBUTING.md
packages/components/package.json

chore: remove unneeded script + update docs

---

.github/workflows/chromatic-main.yml
.github/workflows/quality-check.yml
CONTRIBUTING.md

Works correctly with PR title set to [skip chromatic]:
I didn't manage to get it working with commits in a PR, this should be handled in a follow-up. :(

chore: skip Chromatic via PR title [skip chromatic]

---

.github/workflows/publish-docs.yml

chore: fix docs deployment [skip chromatic]

---

packages/components/custom-elements-manifest.config.js
packages/components/scripts/vendorism.js
packages/components/src/components/button/button.component.ts
packages/components/src/components/button/button.custom.styles.ts
packages/components/src/internal/form.ts
packages/components/src/internal/test.ts
packages/components/src/internal/test/form-control-base-tests.ts
packages/components/src/utilities/localize.ts

This PR updates Shoelace to the latest version 2.12.0.
Closes #255.
The main changes are in internal form handling, especially for buttons. The special button handling was removed in favor of a unified handling in `packages/components/src/internal/form.ts`.
There where also updates to localization. I tested them and they do not trigger any visual changes on our side. Package versions for `@shoelace/localize` did not have to be updated, so this also seems like a small internal refactoring.
> Note that we will have to adjust the changelog manually after the release! This is handeled in #256.
- `pnpm i -r && pnpm build`
- Have a look at storybook if something has changed (e.g. button)
- Have a look at the framework demos. They still work as intended (e.g. vue and react projects still have …

fix: 🤔 Update to shoelace 2.12.0

---

packages/components/CHANGELOG.md

This PR adds additional information about the internal shoelace update to our components package `CHANGELOG.md`.
Closes #256.
I have included **only the relevant points** from shoelaces v2.11.x and v2.12.x and added a link to the original changelog of shoelace.
- Spin up Storybook
- Move to [Packages / Components / Changelog](http://localhost:6006/?path=/docs/packages-components-changelog--docs)
- Validate the data in the section for "v1.2.2".

chore: 🔧 Update components changelog to include shoelace update

---

packages/tokens/src/figma-tokens/_docs.json

This PR fixes an issue with token studio on the radio control.
Closes #264.

fix: 🤔 Tokens of the radio get lost when pushing to GitHub

---

packages/docs/.storybook/preview.ts

docs: add toc to Storybook docs

---

package.json
packages/docs/package.json
patches/@open-wc__lit-helpers@0.5.1.patch
pnpm-lock.yaml

Close https://github.com/synergy-design-system/synergy-design-system/issues/233 by updateing my `storybook-helper` and `pnpm patch` of `open-wc/lit-helper`.
`git fetch && git checkout chore/fix-multiple-lit-versions-error && pnpm i && cd packages/docs && pnpm start`  → No errors anymore in Storybook console.

chore: fix "multiple lit versions" in Storybook [skip chromatic]

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 syn-select focus token and removed multiple-grouping docs

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 added Stepper docs into the Input

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 Fixed syn-Select Prefix Icon docs

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 added-focus-active-docs

---

packages/docs/stories/components/input.stories.ts
packages/tokens/src/figma-tokens/_docs.json

docs: 📚 added Types and Customizing Label Position in Input

---

.vscode/settings.json
packages/_private/vanilla-demo/.eslintrc
packages/_private/vanilla-demo/.gitignore
packages/_private/vanilla-demo/.stylelintrc
packages/_private/vanilla-demo/index.html
packages/_private/vanilla-demo/package.json
packages/_private/vanilla-demo/src/app.css
packages/_private/vanilla-demo/src/main.ts
packages/_private/vanilla-demo/src/vite-env.d.ts
packages/_private/vanilla-demo/tsconfig.json
pnpm-lock.yaml

This PR adds a vanilla html form demo with all currently supported form elements.
Closes #293 
- The numeric input is also part of this, however, as it is not yet merged, it will automatically be available after it gets merged.
- Check out the branch and issue `pnpm install -r`.
- Move to `packages/_private/vanilla-demo` and issue `pnpm start` to spin up the local server
- Play around with the demo and have a look at the form fields validation requirements (e.g. for password or type number).

docs: 📚 add a vanilla demo comprising of all available form elements

---

packages/_private/angular-demo/src/demoform/demoform.component.html
packages/_private/react-demo/src/DemoForm.tsx
packages/_private/vue-demo/src/DemoForm.vue

This PR fixes most of the issues that where not handeled in https://github.com/synergy-design-system/synergy-design-system/pull/301.
- I am currently not sure how we could handle the validation in Angular as it behaves different from the ones in React or Vue. Will have to have a deeper look into this.

docs: 📚 More adjustments for demo projects to use the Synergy Form Field Demo

---

packages/components/package.json
packages/components/scripts/vendorism.js
pnpm-lock.yaml

To make the architecture more robust a change to a published version of `vendorism` (instead of just using the main branch) is needed.

chore: switch to vendorism version from npm

---

packages/_private/angular-demo/src/demofieldset/demofieldset.styles.css
packages/_private/react-demo/src/app.css
packages/_private/vanilla-demo/src/app.css
packages/_private/vue-demo/src/DemoFieldset.vue
packages/docs/src/translations.ts
packages/docs/stories/templates/form.stories.tsx
packages/tokens/src/figma-tokens/_docs.json

This PR adds the suggested changes from design to our contact form template and also updates our demos to use those styles from now on.
Closes #310 
Please have a look at storybook.
It is stated in the ticket that we should draw the description from docs tokens, however as I see it, the description token is not available there. What 
- Check in chromatic if the stories match the requirement.

fix: 🤔 adjust synergy form template

---

packages/tokens/src/figma-tokens/$metadata.json
packages/tokens/src/figma-tokens/$themes.json
packages/tokens/src/figma-tokens/_docs.json
packages/tokens/src/figma-tokens/semantic/overlays.json
packages/tokens/src/figma-tokens/semantic/panels.json

docs: 📚 syn-drawer docs tokens

---

packages/tokens/src/figma-tokens/semantic/button.json
packages/tokens/src/figma-tokens/semantic/input.json

https://github.com/synergy-design-system/design/issues/74

feat: ✨ adjust the size tokens for syn-Input and syn-Button

---

packages/tokens/src/figma-tokens/$themes.json
packages/tokens/src/figma-tokens/globals.json

feat: ✨ added tokens for roundings

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 syn-nav-item

---

packages/tokens/src/figma-tokens/_docs.json

This PR adds missing, removes uneccesary and updates documentation tokens.
- Assets: Logo, Icons, System-icons
- Tokens: Typography, Color, spacing, shadow, border-radius, border-width
- Reordering of Docs-Tokens
https://github.com/synergy-design-system/design/issues/31 
As I changed the order of the tokens, there are some confusing diffs in the file,

docs: 📚 docs token improvements

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 add-docs-syn-tooltip

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚  add syn-side-nav docs

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 add syn-badge

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 add syn-progress-ring

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 add syn-spinner

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 add syn-progress-bar

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 add syn-alert

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 add syn-dialog

---

packages/components/CHANGELOG.md

This PR adds additional information about the internal shoelace update to our components package CHANGELOG.md.
Closes #414 
I have included only the relevant points from shoelaces v2.15.0 and added a link to the original changelog of shoelace.
- Spin up Storybook
- Move to [Packages / Components / Changelog](http://localhost:6006/?path=/docs/packages-components-changelog--docs)
- Validate the data in the section for "v1.16.0".

chore: 🔧  Update components changelog to include shoelace update

---

packages/tokens/src/figma-tokens/globals.json

feat: ✨ opacity-token 50%

---

packages/_private/angular-demo/package.json
packages/_private/angular-demo/src/app.module.ts
packages/angular/README.md
packages/angular/package.json
packages/angular/src/components/checkbox.component.ts
packages/angular/src/components/input.component.ts
packages/angular/src/components/radio-group.component.ts
packages/angular/src/components/select.component.ts
packages/angular/src/components/switch.component.ts
packages/angular/src/components/textarea.component.ts
packages/components/scripts/jobs/angular/createComponents.js
packages/components/scripts/jobs/shared.js
packages/components/scripts/jobs/vue/createWrappers.js
pnpm-lock.yaml

This PR provides a change for the angular wrappers that make form values work with two way data binding.
Closes #397 
- I updated the current angular (dev) dependencies on `@synergy-design-system/angular` and the angular demo to the latest version.
- I opted to move parts of the vue and angular build scripts that where copied over to the `shared.js` build utilities to lessen code duplication.
- After talking to the stakeholder it came apperant that we only need this for the input value fields and __not__ for all attributes.
- Check out this branch and build world.
- Move to `packages/_private/angular-demo` and exchange the code for the home component to the snippets defined below.
- Start the angular demo and type text into the input field or change the checkbox or select values. You …

feat: ✨ Angular: Allow two way data binding component wrappers

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 syn-details

---

packages/tokens/src/figma-tokens/_docs.json

docs: 📚 syn-breadcrumb

---

.github/workflows/quality-check.yml
packages/_private/e2e-demo-test/playwright.config.ts

E2E job should be reflected appropriately
#481

chore: revised workflow wordings

---

CONTRIBUTING.md

Minor text fixes in the contrib doc
no issue available
Just read through the md file

CONTRIBUTING text

---

packages/docs/stories/components/card.stories.ts
packages/tokens/src/figma-tokens/_docs.json

docs: 📚 added docs for Sharp Card

---

packages/components/src/components/select/select.custom.styles.ts
packages/docs/stories/components/select.stories.ts
packages/tokens/src/figma-tokens/_docs.json

fix: 🤔 added invalid state to syn-select

---

packages/tokens/src/figma-tokens/_docs.json

feat: ✨ Added help-text for checkbox and switch

---

packages/styles/build/jobs/copyModules.js

I had problems in building the styles package. Apparently the promise resolvement was wrong. :)

chore: fix wrong promise resolvement in build step

---

.github/ISSUE_TEMPLATE/chore.md
.github/ISSUE_TEMPLATE/component-request-feature.md
.github/ISSUE_TEMPLATE/component-request-new-component.md
.github/ISSUE_TEMPLATE/generic-bug.md
.github/ISSUE_TEMPLATE/generic-docs.md
.github/ISSUE_TEMPLATE/generic-feature.md

- replaced bug emoticon
- removed unneeded issue labels
- beautifying

docs: 📚 Remove GH template labels

---

packages/angular/LIMITATIONS.md
packages/components/LIMITATIONS.md
packages/vue/LIMITATIONS.md

docs: 📚 Revised LIMITATIONS docu

---

packages/docs/.storybook/preview-head.html

docs: 📚 Fix some docs pages no longer scrollable

---

packages/tokens/src/figma-tokens/_docs.json

add link list and tag group docs token

docs: 📚 add link list and tag group docs token

---

packages/components/src/components/combobox/combobox.component.ts

This PR fixen an issue with our new `<syn-combobox>` that made keyboard navigation unusable when used in our framework wrappers. For issue reasons, see reviewer notes below.
Closes #632 
The issue stemmed from the fact that the active navigation item was cached in the component (e.g. `this.currentOption`, but the DOM-reference was dropped as the frameworks tended to recreate the DOM (partially) and therefore invalid in the component. The fix was searching  through the active element DOM-List to find the active element (flagged via the `current` attribute of the `<syn-option>`.
- Check out this branch (**Mandatory**, as this is not easily reproducible with standard HTML!)
- Start each framework demo (angular, vue, react, vanilla)
- Play around with the provided nationality field. Use …

fix: 🐛 syn-combobox: Keyboard navigation not working after text was entered

---

packages/assets/package.json

fix: 🐛 Assets release process

---

packages/components/LIMITATIONS.md
packages/docs/stories/templates/form.stories.tsx

This PR adds an entry in the "Known Issues" documentation for this problem
Closes #612 
Have a look at the "Known issues" documentation: http://localhost:6006/?path=/docs/limitations-components--docs

docs: 📚 Known issue entry for wrong rendering order with "container-type"

---

packages/components/CHANGELOG.md

Update changelog for collective issues

docs: 📚 Update changelog

---

packages/mcp/CHANGELOG.md
packages/mcp/package.json
pnpm-lock.yaml

This PR hopefully fixes the problems with the mcp package release
Closes #993

chore: 🔧 Fix mcp version to be aligned with released version
